// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbtzakkfeveiwnlakbap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZidHpha2tmZXZlaXdubGFrYmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODc3MDYsImV4cCI6MjA1ODQ2MzcwNn0.TVUBCMVFdsV0T5AE-6JZeNdCFGXNl4YyG8fzYmYkrZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);